server:
  port: 8080
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengvipin/config-repo.git
          username: XXXXXX
          password: XXXXXX
          basedir: C:\Users\Administrator\Desktop\springcloud_sell\config\basedir

  rabbitmq:
    host: 192.168.211.211
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

eureka:
  client:
    service-url:
      defaultZone: http://192.168.211.211:8761/eureka/
