server:
  port: 8700
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhengvipin/config-repo.git
          username: zhengvipin
          password: 1004zwpxhzxq0518
#          basedir: C:\Users\Administrator\Desktop\springcloud_sell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/