server:
  port: 8761
# 注册中心地址
spring:
  application:
    name: eureka
eureka:
  client:
    service-url:
      # 生产环境要启动多个eureka实例，实现高可用
#      defaultZone: http://localhost:8762/eureka/,http://localhost:8763/eureka/
      defaultZone: http://localhost:8761/eureka/
    # 是否要在注册中心注册自己
    register-with-eureka: false
    # 是否要在注册中心拉取服务列表
    fetch-registry: false
  server:
    # 是否开启自我保护机制（开发环境建议关闭）
    enable-self-preservation: false
