spring:
  application:
    name: client
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
      defaultZone: http://localhost:8761/eureka/
  # 配置当前实例的主机名字
#  instance:
#    hostname: clientName

